In [31]:
# Numpy has high-level number objects: integers, floating point
# It has containers: lists(costless insertion and append), dictionaries(fast lookup)

# Numpy prvides :-
# 1. Entension package to python for multi-dimensional arrays.
# 2. Closer to hardware(efficiency)
# 3. Designed for scientific computation(convinience).
# 4. Also known as array oriented computing.

# Creating a numpy array takes less time than creating a list in Python.

# 1-D Array is called a Vector.
# 2-D Array is called a Matrix.
# n-D Array is called a Tensor.
                              

In [32]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

# Create a numpy array 0 -> 9
print(np.arange(10)) 

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [33]:
# Manual contruction of array

a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(a.ndim) # 2-dimention array
print(a.shape) # rows * cols
print(len(a)) # returns the size of the first dimension(rows in this case)

2
(2, 4)
2


In [34]:
# 3-dimensional array --> Very difficult to visualize --> A 3-dimensional array is basically a cuboid.
b = np.array([[[1, 2], [3, 4]],[[5, 6],[7, 8]]])
print(b)
print(b.ndim)
print(b.shape)
print(len(b))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
2


In [49]:
# Functions for creating arrays

# Using arange
a = np.arange(1, 10, 2) #  start, end(exclusive), step_size
print(a)

# Using linspace --> Dividing a line into the number of points passed into the method
b = np.linspace(0, 1, 6) # start, end(exclusive), num_of_points
print(b)

# Common arrays
c = np.ones((3, 3))
print(c)

d = np.zeros((3, 3))
print(d)

# Return an identity matrix [Diagonal elements are 1 and non-diagonal elements are 0]
e = np.eye(3, 3)
print(e)

# Create array using diag function
#  The elements passed to this method are in the diagonals and rest of the elems in the matrix are 0.
f = np.diag([1, 2, 3, 4])
print(f)

# Extract Diagonals
print(np.diag(f))

# Create array using random
g = np.random.rand(4)
print(g)

[1 3 5 7 9]
[0.  0.2 0.4 0.6 0.8 1. ]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1 2 3 4]
[0.13044941 0.21804204 0.80415981 0.8950369 ]


In [58]:
# Basic datatypes

a = np.arange(10)
print(a.dtype)

# Create a floating point dtype array
b = np.arange(10, dtype='float64')
print(b)

# Complex datatype
c = np.array([1 + 2j, 2 + 4j])
print(c.dtype)

# Boolean datatype
d = np.array([True, False])
print(d.dtype)

int64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
complex128
bool


In [68]:
# Indexing and Slicing

# Indexing
a = np.diag([1, 2, 3])
print(a[2][2])

# Assigning Value
a[2][1] = 5
print(a[2][1])

# Slicing :- a[start: end(exclusive): step_size]
print(a[0:3:2][1])


3
5
[0 5 3]


In [76]:
# Filtering in numpy using mask

# Get only the elements which are even
a = np.random.randint(0, 20, 15)
print(a)
mask = a % 2 == 0

extract_from_a = a[mask]
print(extract_from_a)

[11 11 19  9  8  5  7  9  6 11  4 19  2 17  3]
[8 6 4 2]


In [79]:
# Numerical operations on Numpy
a = np.array([1, 2, 3, 4])

#Element wise operations
print(a + 1) # Scalar addition
print(a ** 2)


[2 3 4 5]
[ 1  4  9 16]


In [82]:
# Arithmetic elementwise operations
a = np.array([1, 2, 3, 4])
b = np.ones(4) + 1

print(a - b)
print(a * b) # Element wise multiplication

[-1.  0.  1.  2.]
[2. 4. 6. 8.]


In [86]:
# Matrix multiplication
c = np.diag([1, 2, 3, 4])

# We can do matrix-multiplication using both the methods
print(c * c) 
print("*********************************")
print(c.dot(c)) 

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*********************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [87]:
# Comparisons

a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])

print(a == b)
print(a > b)

[False  True False  True]
[False False  True False]


In [89]:
# Array-wise comparison
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

print(np.array_equal(a, b))
print(np.array_equal(a, c))

False
True


In [107]:
# Logical operations

a = np.array([1, 1, 0, 0], dtype = bool)
b = np.array([1, 0, 1, 0], dtype = bool)

print(np.logical_or(a, b))
print(np.logical_and(a, b))
print(np.all([True, True, False])) # Logical AND
print(np.any([True, True, False])) # Logical OR

[ True  True  True False]
[ True False False False]
False
True


In [108]:
# Mathematical functions in Numpy

a = np.arange(1, 5)

print(a)
print(np.sin(a))
print(np.log(a))
print(np.exp(a)) # e ^ x

[1 2 3 4]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [105]:
# Basic Reductions

x = np.array([1, 2, 3, 4])
print(np.sum(x))
print(x.min())
print(x.max())
print(x.argmin()) # Index of min element
print(y.argmax()) # Index of max element

y = np.array([[1, 1], [2, 2]])
print(y)
print(y.sum(axis = 1))

10
1
4
0
2
[[1 1]
 [2 2]]
[2 4]


In [115]:
# Statistics
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])

print(x)
print(y)
print("*****************************************")
print(x.mean())
print(np.median(x))
print(np.median(y, axis = 1)) # Last Axis (X Axis)
print(x.std()) # STandard Deviation

[1 2 3 1]
[[1 2 3]
 [5 6 1]]
*****************************************
1.75
1.5
[2. 5.]
0.82915619758885


# Numpy operations on populations.txt file-It has the populations of hares, lynxes and carrots during 20 years

In [123]:
#Load data into numpy array object
data = np.loadtxt('populations.txt')

In [124]:
print(data)

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


In [126]:
year, hares, lynxex, carrots = data.T # Columns to variables
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [131]:
# The mean population over time
populations = data[:,1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [136]:
# Std deviation
print(populations.std(axis = 0))

# Which species has the highest population each year?
print(np.argmax(populations, axis = 1))

[20897.90645809 16254.59153691  3322.50622558]
[2 2 0 0 1 1 2 2 2 2 2 2 0 0 0 1 2 2 2 2 2]


In [147]:
# Broadcasting operation in Numpy
# a mechanism that allows for efficient arithmetic operations on arrays of different 
# shapes by implicitly expanding (or "broadcasting") the smaller array to match the 
# larger array's shape

a1 = np.tile(np.arange(0, 40, 10), (3, 1)) # Replicate in 3 times in the rows 1 time.
print(a1)
print("******************************************")
a1 = a1.T # Transpose of a1
print(a1)

print("********************************************")
a2 = np.array([0, 1, 2])
print(a2)

print("**********************************************")
print(a1 + a2)

print("***********************************************")
a3 = np.arange(0, 40 , 10)
a3 = a3[:, np.newaxis] # Adds a new axis making it a 2-D array.
print(a3)

print("*************************************************")
print(a2 + a3)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
******************************************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
********************************************
[0 1 2]
**********************************************
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
***********************************************
[[ 0]
 [10]
 [20]
 [30]]
*************************************************
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [157]:
# Array Shape Manipulations

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ravel()) # Flattens the array into a 1-D array
print(a.T) # Transpose of the array
print(a.T.ravel())

print("**********************************************")
#Reshaping
b = a.ravel()
b = b.reshape((2, 3))
print(b)

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[1 4 2 5 3 6]
**********************************************
[[1 2 3]
 [4 5 6]]


In [162]:
# Adding a new dimension to an array / matrix
z = np.array([1, 2, 3])
z[:, np.newaxis]

array([[1],
       [2],
       [3]])